#!/usr/bin/env node
// Copied into a bundle and executed only by its pinned bundle-local Node runtime.
import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import http from 'node:http';
import net from 'node:net';
import path from 'node:path';

const CSP = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' blob:; media-src 'self' blob:; connect-src 'self' http://127.0.0.1:*; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";
const PRIVATE_PROTOCOL_TIMEOUT_MS = 24 * 60 * 60 * 1000;
const SANDBOX_PROFILE_SHA256 = '3590d5c646ed3ca0e1769927797a87ae49bb1ce3920e40218a547d480beef481';
const sandboxMarker = globalThis[Symbol.for('sam-goal.manual-review.sandbox-v1')];
if (sandboxMarker?.active !== true || sandboxMarker?.profileSha256 !== SANDBOX_PROFILE_SHA256) throw Object.assign(new Error('sandbox_marker_required'), { code: 'sandbox_marker_required' });

const fail = (code) => { throw Object.assign(new Error(code), { code }); };
const sha256 = (value) => crypto.createHash('sha256').update(value).digest('hex');
const rawCompare = (a, b) => Buffer.compare(Buffer.from(a, 'utf8'), Buffer.from(b, 'utf8'));
const canonical = (value) => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort(rawCompare).map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}` : JSON.stringify(value);
const processBytes = (value) => Buffer.from(`${canonical(value)}\n`, 'utf8');
const equal = (left, right) => canonical(left) === canonical(right);
const exactKeys = (value, keys, code = 'object_not_closed') => { if (!value || typeof value !== 'object' || Array.isArray(value) || !equal(Object.keys(value).sort(rawCompare), [...keys].sort(rawCompare))) fail(code); };

class StrictJsonParser {
  constructor(text) { this.text = text; this.index = 0; }
  ws() { while ([' ', '\t', '\n', '\r'].includes(this.text[this.index])) this.index += 1; }
  parse() { this.ws(); const value = this.value(); this.ws(); if (this.index !== this.text.length) fail('json_trailing_data'); return value; }
  value() { this.ws(); const c = this.text[this.index]; if (c === '{') return this.object(); if (c === '[') return this.array(); if (c === '"') return this.string(); if (this.text.startsWith('true', this.index)) { this.index += 4; return true; } if (this.text.startsWith('false', this.index)) { this.index += 5; return false; } if (this.text.startsWith('null', this.index)) { this.index += 4; return null; } return this.number(); }
  string() { const start = this.index++; for (;;) { if (this.index >= this.text.length) fail('json_unterminated_string'); const c = this.text[this.index++]; if (c === '"') break; if (c === '\\') this.index += 1; else if (c.charCodeAt(0) < 0x20) fail('json_control_character'); } try { return JSON.parse(this.text.slice(start, this.index)); } catch { fail('json_invalid_string'); } }
  number() { const match = this.text.slice(this.index).match(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/u); if (!match) fail('json_invalid_value'); this.index += match[0].length; const value = Number(match[0]); if (!Number.isFinite(value)) fail('non_finite_number'); return value; }
  array() { const value = []; this.index += 1; this.ws(); if (this.text[this.index] === ']') { this.index += 1; return value; } for (;;) { value.push(this.value()); this.ws(); const c = this.text[this.index++]; if (c === ']') return value; if (c !== ',') fail('json_invalid_array'); } }
  object() { const value = Object.create(null); const seen = new Set(); this.index += 1; this.ws(); if (this.text[this.index] === '}') { this.index += 1; return value; } for (;;) { this.ws(); if (this.text[this.index] !== '"') fail('json_object_key_required'); const key = this.string(); if (seen.has(key)) fail('duplicate_json_key'); seen.add(key); this.ws(); if (this.text[this.index++] !== ':') fail('json_colon_required'); Object.defineProperty(value, key, { configurable: true, enumerable: true, value: this.value(), writable: true }); this.ws(); const c = this.text[this.index++]; if (c === '}') return value; if (c !== ',') fail('json_invalid_object'); } }
}
function parseJson(bytes, { canonicalProcess = false } = {}) { if (!Buffer.isBuffer(bytes)) bytes = Buffer.from(bytes); if (bytes.length >= 3 && bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) fail('utf8_bom_forbidden'); const text = bytes.toString('utf8'); if (!Buffer.from(text).equals(bytes)) fail('invalid_utf8'); const value = new StrictJsonParser(text).parse(); if (canonicalProcess && !processBytes(value).equals(bytes)) fail('process_json_not_canonical'); return value; }

function parseArgs(argv) { const result = {}; for (let index = 0; index < argv.length; index += 2) { const key = argv[index]; const value = argv[index + 1]; if (!key?.startsWith('--') || value === undefined || Object.hasOwn(result, key)) fail('cli_flag_invalid'); result[key] = value; } const keys = Object.hasOwn(result, '--test-fault') ? ['--bundle-root', '--host-repository-probe', '--sibling-probe', '--test-fault'] : ['--bundle-root', '--host-repository-probe', '--sibling-probe']; exactKeys(result, keys, 'cli_flag_invalid'); if (!path.isAbsolute(result['--bundle-root']) || !path.isAbsolute(result['--host-repository-probe']) || !path.isAbsolute(result['--sibling-probe'])) fail('cli_flag_invalid'); if (Object.hasOwn(result, '--test-fault') && (process.env.NODE_ENV !== 'test' || process.env.SAM_GOAL_MANUAL_REVIEW_OPS_V1_RUNTIME_TEST !== '1' || !['startup-hang','oversize-ready','duplicate-key-ready','malformed-ready','extra-ready-line','crash-after-ready'].includes(result['--test-fault']))) fail('test_hook_invalid'); return result; }

const args = parseArgs(process.argv.slice(2));
const testFault = args['--test-fault'] ?? null;
if (testFault === 'startup-hang') await new Promise(() => setInterval(() => {}, 1_000));
const root = fs.realpathSync(args['--bundle-root']);
const rootInitial = fs.lstatSync(root);
if (!rootInitial.isDirectory() || rootInitial.isSymbolicLink()) fail('bundle_root_invalid');
const events = []; let eventSequence = 0;
function record(logicalPath, operation, result) { events.push({ sequence: ++eventSequence, logicalPath, operation, result }); }
function verifyRoot() { const current = fs.lstatSync(root); if (!current.isDirectory() || current.isSymbolicLink() || current.dev !== rootInitial.dev || current.ino !== rootInitial.ino || current.mode !== rootInitial.mode || fs.realpathSync(root) !== root) fail('bundle_root_identity_drift'); }
function safeLogical(logicalPath) { if (typeof logicalPath !== 'string' || !logicalPath || logicalPath.startsWith('/') || logicalPath.includes('..') || logicalPath.includes('\\') || logicalPath.split('/').some((part) => !part || part === '.' || part === '..')) fail('path_denied'); }
function checkParents(absolute) { verifyRoot(); const relative = path.relative(root, absolute); if (relative.startsWith('..') || path.isAbsolute(relative)) fail('path_denied'); let current = root; const parts = relative.split(path.sep); for (const part of parts.slice(0, -1)) { current = path.join(current, part); const stat = fs.lstatSync(current); if (!stat.isDirectory() || stat.isSymbolicLink()) fail('path_parent_invalid'); } }
function stableReadAbsolute(absolute, logicalPath, expected) {
  checkParents(absolute); const initial = fs.lstatSync(absolute); if (!initial.isFile() || initial.isSymbolicLink() || initial.nlink !== 1) fail('sealed_file_type_invalid');
  const fd = fs.openSync(absolute, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0) | (fs.constants.O_NONBLOCK ?? 0));
  try { const held = fs.fstatSync(fd); const first = Buffer.alloc(held.size); const second = Buffer.alloc(held.size); let offset = 0; while (offset < first.length) { const count = fs.readSync(fd, first, offset, first.length - offset, offset); if (!count) fail('sealed_file_short_read'); offset += count; } offset = 0; while (offset < second.length) { const count = fs.readSync(fd, second, offset, second.length - offset, offset); if (!count) fail('sealed_file_short_read'); offset += count; } const post = fs.lstatSync(absolute); if (!first.equals(second) || held.dev !== initial.dev || held.ino !== initial.ino || held.mode !== initial.mode || held.nlink !== initial.nlink || held.size !== initial.size || post.dev !== initial.dev || post.ino !== initial.ino || post.mode !== initial.mode || post.nlink !== initial.nlink || post.size !== initial.size) fail('sealed_file_identity_drift'); if (expected && (first.length !== expected.bytes || sha256(first) !== expected.sha256 || Boolean(held.mode & 0o111) !== expected.executable || (held.mode & 0o7777) !== expected.mode)) fail('sealed_file_descriptor_drift'); record(logicalPath, 'read', 'allowed'); return first; } finally { fs.closeSync(fd); }
}

function holdAbsolute(absolute, logicalPath, expected) {
  checkParents(absolute); const ancestors = []; let cursor = path.dirname(absolute); while (cursor.startsWith(root) && cursor !== root) { const stat = fs.lstatSync(cursor); if (!stat.isDirectory() || stat.isSymbolicLink()) fail('path_parent_invalid'); ancestors.push({ path: cursor, dev: stat.dev, ino: stat.ino, mode: stat.mode }); cursor = path.dirname(cursor); }
  const initial = fs.lstatSync(absolute); if (!initial.isFile() || initial.isSymbolicLink() || initial.nlink !== 1) fail('sealed_file_type_invalid'); const fd = fs.openSync(absolute, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0) | (fs.constants.O_NONBLOCK ?? 0));
  try { const held = fs.fstatSync(fd); const bytes = Buffer.alloc(held.size); let offset = 0; while (offset < bytes.length) { const count = fs.readSync(fd, bytes, offset, bytes.length - offset, offset); if (!count) fail('sealed_file_short_read'); offset += count; } const post = fs.lstatSync(absolute); if (held.dev !== initial.dev || held.ino !== initial.ino || held.mode !== initial.mode || held.nlink !== initial.nlink || held.size !== initial.size || post.dev !== initial.dev || post.ino !== initial.ino || post.mode !== initial.mode || post.nlink !== initial.nlink || post.size !== initial.size || bytes.length !== expected.bytes || sha256(bytes) !== expected.sha256 || Boolean(held.mode & 0o111) !== expected.executable || (held.mode & 0o7777) !== expected.mode) fail('sealed_file_descriptor_drift'); record(logicalPath, 'read', 'allowed'); return { absolute, logicalPath, fd, ancestors, descriptor: expected, identity: { dev: held.dev, ino: held.ino, mode: held.mode, nlink: held.nlink, size: held.size } }; } catch (error) { fs.closeSync(fd); throw error; }
}
function revalidateHeld(snapshot, { returnBytes = false } = {}) {
  verifyRoot(); for (const ancestor of snapshot.ancestors) { const stat = fs.lstatSync(ancestor.path); if (!stat.isDirectory() || stat.isSymbolicLink() || stat.dev !== ancestor.dev || stat.ino !== ancestor.ino || stat.mode !== ancestor.mode) fail('held_ancestor_identity_drift'); }
  const held = fs.fstatSync(snapshot.fd); const post = fs.lstatSync(snapshot.absolute); const bytes = Buffer.alloc(snapshot.identity.size); let offset = 0; while (offset < bytes.length) { const count = fs.readSync(snapshot.fd, bytes, offset, bytes.length - offset, offset); if (!count) fail('sealed_file_short_read'); offset += count; }
  if (!held.isFile() || held.dev !== snapshot.identity.dev || held.ino !== snapshot.identity.ino || held.mode !== snapshot.identity.mode || held.nlink !== snapshot.identity.nlink || held.size !== snapshot.identity.size || !post.isFile() || post.isSymbolicLink() || post.dev !== snapshot.identity.dev || post.ino !== snapshot.identity.ino || post.mode !== snapshot.identity.mode || post.nlink !== snapshot.identity.nlink || post.size !== snapshot.identity.size || bytes.length !== snapshot.descriptor.bytes || sha256(bytes) !== snapshot.descriptor.sha256) fail('held_file_identity_drift'); record(snapshot.logicalPath, 'read', 'allowed'); return returnBytes ? bytes : undefined;
}

const manifestLogical = 'immutable/bundle-manifest.json';
const manifestPath = path.join(root, manifestLogical);
const manifestBytes = stableReadAbsolute(manifestPath, manifestLogical);
const manifestDescriptor = { bytes: manifestBytes.length, sha256: sha256(manifestBytes), executable: false, mode: 0o400 };
if ((fs.lstatSync(manifestPath).mode & 0o7777) !== 0o400) fail('bundle_manifest_mode_invalid');
const manifest = parseJson(manifestBytes, { canonicalProcess: true });
if (manifest.artifactType !== 'sam-goal-review-bundle-manifest-v1' || manifest.schemaVersion !== 1 || !Array.isArray(manifest.immutableAssets) || !Array.isArray(manifest.mutableLogicalRoots) || !equal(manifest.mutableLogicalRoots, ['mutable'])) fail('bundle_manifest_invalid');
const immutable = new Map();
for (const asset of manifest.immutableAssets) { exactKeys(asset, ['logicalPath', 'bytes', 'sha256', 'mediaType', 'executable', 'assetClass'], 'immutable_descriptor_not_closed'); safeLogical(asset.logicalPath); if (!asset.logicalPath.startsWith('immutable/') || !Number.isSafeInteger(asset.bytes) || asset.bytes < 1 || !/^[0-9a-f]{64}$/u.test(asset.sha256) || typeof asset.executable !== 'boolean' || immutable.has(asset.logicalPath)) fail('immutable_descriptor_invalid'); immutable.set(asset.logicalPath, asset); }
if (sha256(Buffer.from(canonical([...immutable.values()].sort((a, b) => rawCompare(a.logicalPath, b.logicalPath))))) !== manifest.immutableAssetSetSha256) fail('immutable_asset_set_hash_drift');
const PRESENTATION_VIEWER_PATHS = ['immutable/viewer/app.js','immutable/viewer/core.mjs','immutable/viewer/exact-still-decoder.js','immutable/viewer/index.html','immutable/viewer/schema-validator.mjs','immutable/viewer/style.css'];
const presentationViewerAssets = PRESENTATION_VIEWER_PATHS.map((logicalPath) => { const asset = immutable.get(logicalPath); if (!asset) fail('presentation_contract_mismatch'); return { logicalPath, bytes: asset.bytes, sha256: asset.sha256 }; }).sort((left, right) => rawCompare(left.logicalPath, right.logicalPath));
const presentationDescriptor = { artifactType: 'sam-goal-manual-review-presentation-contract-v1', schemaVersion: 1, authorityClass: 'process-evidence-only', compilerInput: false, p0Authority: false, interfaceId: 'sam_goal.manual_review_operations', interfaceVersion: 3, rules: { defaultViewMode: 'fit', fitEntireFrame: true, uniformScale: true, clippingAllowed: false, mirrored: false, contentEvidenceTargetContainsOnlySourceFrame: true, intrinsicDecodePixelsUnchanged: true, pointerMapping: 'inverse-uniform-fit-to-intrinsic-source-pixels' }, evidenceTargets: { selectorAttribute: 'data-sam-goal-evidence-target', blind: 'blind-exact-source-frame', reveal: 'reveal-exact-source-frame' }, viewModes: ['fit','one-to-one'], viewerAssets: presentationViewerAssets };
const currentPresentationContractSha256 = sha256(processBytes(presentationDescriptor));
if (manifest.presentationContractSha256 !== currentPresentationContractSha256) fail('presentation_contract_mismatch');
const REVEAL_FIXED_PATHS = ['fixed/access-policy.json','fixed/c0-ledger.json','fixed/disagreement-skeleton.json','fixed/raw-ab-report.json','fixed/reveal-receipt.json','fixed/review-a-export-receipt.json','fixed/review-a.json','fixed/review-b-export-receipt.json','fixed/review-b.json'];
const fixed = new Map();

function resolveAllowed(logicalPath, operation = 'read') { safeLogical(logicalPath); const mutable = logicalPath === 'mutable' || logicalPath.startsWith('mutable/'); const fixedRead = operation === 'read' && fixed.has(logicalPath); if ((operation === 'read' && !immutable.has(logicalPath) && !mutable && !fixedRead) || (operation !== 'read' && !mutable)) fail('path_denied'); const absolute = path.join(root, logicalPath); checkParents(absolute); return absolute; }
const heldManifest = holdAbsolute(manifestPath, manifestLogical, manifestDescriptor);
const heldImmutable = new Map();
for (const asset of immutable.values()) heldImmutable.set(asset.logicalPath, holdAbsolute(resolveAllowed(asset.logicalPath), asset.logicalPath, { ...asset, mode: asset.executable ? 0o500 : 0o400 }));
const heldFixed = new Map();
if (manifest.mode === 'adjudication-reveal') {
  const fixedRoot = path.join(root, 'fixed'); const entries = fs.readdirSync(fixedRoot).map((name) => `fixed/${name}`).sort(rawCompare); if (!equal(entries, REVEAL_FIXED_PATHS)) fail('reveal_fixed_set_invalid');
  for (const logicalPath of REVEAL_FIXED_PATHS) { const absolute = path.join(root, logicalPath); const bytes = stableReadAbsolute(absolute, logicalPath); const descriptor = { logicalPath, bytes: bytes.length, sha256: sha256(bytes), executable: false, mode: 0o400 }; fixed.set(logicalPath, descriptor); heldFixed.set(logicalPath, holdAbsolute(absolute, logicalPath, descriptor)); }
} else { try { fs.lstatSync(path.join(root, 'fixed')); fail('blind_fixed_root_forbidden'); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
function readImmutable(logicalPath) { const snapshot = heldImmutable.get(logicalPath); if (!snapshot) fail('immutable_asset_undeclared'); return revalidateHeld(snapshot, { returnBytes: true }); }
function readFixed(logicalPath) { const snapshot = heldFixed.get(logicalPath); if (!snapshot) fail('fixed_asset_undeclared'); return revalidateHeld(snapshot, { returnBytes: true }); }
function verifyImmutableSet() { const descriptors = [...immutable.values()].sort((a, b) => rawCompare(a.logicalPath, b.logicalPath)); if (!equal(descriptors.map((item) => item.logicalPath), [...immutable.keys()].sort(rawCompare))) fail('immutable_asset_set_invalid'); revalidateHeld(heldManifest); for (const descriptor of descriptors) revalidateHeld(heldImmutable.get(descriptor.logicalPath)); for (const logicalPath of REVEAL_FIXED_PATHS) if (manifest.mode === 'adjudication-reveal') revalidateHeld(heldFixed.get(logicalPath)); verifyRoot(); }

function actualDeniedFileProbe(name, absolutePath) { try { const fd = fs.openSync(absolutePath, fs.constants.O_RDONLY); fs.closeSync(fd); record(absolutePath, 'read', 'allowed'); return { name, attempted: true, denied: false }; } catch (error) { const denied = ['ERR_ACCESS_DENIED', 'EPERM', 'EACCES'].includes(error.code); record(absolutePath, 'read', denied ? 'denied' : 'allowed'); return { name, attempted: true, denied }; } }
async function actualDeniedNetworkProbe(host) { return new Promise((resolve) => { const socket = net.createConnection({ host, port: 9 }); let settled = false; const finish = (denied) => { if (settled) return; settled = true; socket.destroy(); record(`${host}:9`, 'connect', denied ? 'denied' : 'allowed'); resolve({ name: 'non-loopback', attempted: true, host, denied }); }; socket.once('connect', () => finish(false)); socket.once('error', (error) => finish(['EPERM', 'EACCES', 'ERR_ACCESS_DENIED'].includes(error.code))); setTimeout(() => finish(false), 1000).unref(); }); }

verifyImmutableSet();
const negativeProbeResults = [actualDeniedFileProbe('host-repository', args['--host-repository-probe']), actualDeniedFileProbe('sibling-bundle', args['--sibling-probe']), await actualDeniedNetworkProbe('198.51.100.1')];
if (negativeProbeResults.some((probe) => !probe.denied)) fail('deny_default_probe_failed');

const decoderSource = readImmutable('immutable/viewer/exact-still-decoder.js');
const exactDecoder = await import(`data:text/javascript;base64,${decoderSource.toString('base64')}`);
const decoderManifestBytes = readImmutable('immutable/authority/decoder-manifest.jsonl');
if (!decoderManifestBytes.toString('utf8').endsWith('\n')) fail('decoder_manifest_invalid');
const decoderRows = decoderManifestBytes.toString('utf8').slice(0, -1).split('\n').map((line) => parseJson(Buffer.from(line)));
const sourceInventory = parseJson(readImmutable('immutable/authority/source-inventory.json'));
const sourceMetadata = new Map();
for (const source of manifest.sourceBinding?.sources ?? []) { const rows = decoderRows.filter((row) => row.clipId === source.clipId); const inventory = sourceInventory.paired?.find((item) => item.clipId === source.clipId); const logicalPath = `immutable/sources/${source.clipId}.mp4`; const asset = immutable.get(logicalPath); if (!asset || asset.sha256 !== source.sha256 || asset.bytes !== source.bytes || !rows.length || !inventory || inventory.video.sha256 !== source.sha256 || inventory.video.bytes !== source.bytes) fail('source_binding_invalid'); const parsed = exactDecoder.parseIsoBmffVideo(readImmutable(logicalPath), rows.length); exactDecoder.verifyExactManifest(parsed, rows, source.clipId); if (parsed.config.codedWidth !== inventory.media.width || parsed.config.codedHeight !== inventory.media.height) fail('source_geometry_binding_invalid'); sourceMetadata.set(source.clipId, { codedWidth: inventory.media.width, codedHeight: inventory.media.height, displayWidth: inventory.media.width, displayHeight: inventory.media.height, sourceByteSha256: asset.sha256, rowCount: rows.length }); }
if (sourceMetadata.size !== 7 || decoderRows.length !== 6711) fail('source_binding_invalid');
let revealCore = null; let revealReviewA = null; let revealReviewB = null; let revealC0 = null; let revealSkeleton = null; let revealReceiptByteSha256 = null;
const revealFixedDescriptors = [...fixed.values()].map(({ logicalPath, bytes, sha256: digest }) => ({ logicalPath, bytes, sha256: digest })).sort((a, b) => rawCompare(a.logicalPath, b.logicalPath));
const revealFixedInputSetSha256 = sha256(processBytes(revealFixedDescriptors));
if (manifest.mode === 'adjudication-reveal') {
  revealReviewA = parseJson(readFixed('fixed/review-a.json'), { canonicalProcess: true }); revealReviewB = parseJson(readFixed('fixed/review-b.json'), { canonicalProcess: true }); revealC0 = parseJson(readFixed('fixed/c0-ledger.json'), { canonicalProcess: true }); revealSkeleton = parseJson(readFixed('fixed/disagreement-skeleton.json'), { canonicalProcess: true }); revealReceiptByteSha256 = sha256(readFixed('fixed/reveal-receipt.json'));
  const coreBytes = readImmutable('immutable/viewer/core.mjs'); const source = coreBytes.toString('utf8'); const marker = "export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');"; if (source.split(marker).length !== 2) fail('reveal_core_binding_invalid'); const transformed = source.replace(marker, `export const REPO_ROOT = ${JSON.stringify(root)};`); revealCore = await import(`data:text/javascript;base64,${Buffer.from(transformed).toString('base64')}`);
}

function readMutableSnapshot(logicalPath, { recordEvent = true, expectedMode = 0o600 } = {}) { const target = resolveAllowed(logicalPath, 'read'); const ancestors = []; let cursor = path.dirname(target); while (cursor.startsWith(root) && cursor !== root) { const stat = fs.lstatSync(cursor); if (!stat.isDirectory() || stat.isSymbolicLink()) fail('mutable_ancestor_invalid'); ancestors.push({ path: cursor, dev: stat.dev, ino: stat.ino, mode: stat.mode }); cursor = path.dirname(cursor); } const initial = fs.lstatSync(target); if (!initial.isFile() || initial.isSymbolicLink() || initial.nlink !== 1 || (initial.mode & 0o7777) !== expectedMode) fail('mutable_file_invalid'); const fd = fs.openSync(target, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0) | (fs.constants.O_NONBLOCK ?? 0)); try { const held = fs.fstatSync(fd); const read = () => { const bytes = Buffer.alloc(held.size); let offset = 0; while (offset < bytes.length) { const count = fs.readSync(fd, bytes, offset, bytes.length - offset, offset); if (!count) fail('mutable_short_read'); offset += count; } return bytes; }; const bytes = read(); const second = read(); const post = fs.lstatSync(target); if (!bytes.equals(second) || held.dev !== initial.dev || held.ino !== initial.ino || held.mode !== initial.mode || held.size !== initial.size || held.nlink !== initial.nlink || post.dev !== initial.dev || post.ino !== initial.ino || post.mode !== initial.mode || post.size !== initial.size || post.nlink !== initial.nlink) fail('mutable_identity_drift'); if (recordEvent) record(logicalPath, 'read', 'allowed'); return { logicalPath, target, fd, bytes, ancestors, expectedMode, identity: { dev: held.dev, ino: held.ino, mode: held.mode, size: held.size, nlink: held.nlink }, sha256: sha256(bytes) }; } catch (error) { fs.closeSync(fd); throw error; } }
function closeMutable(snapshot) { if (snapshot?.fd !== undefined) { fs.closeSync(snapshot.fd); snapshot.fd = undefined; } }
function revalidateMutable(snapshot) { verifyRoot(); for (const ancestor of snapshot.ancestors) { const stat = fs.lstatSync(ancestor.path); if (!stat.isDirectory() || stat.isSymbolicLink() || stat.dev !== ancestor.dev || stat.ino !== ancestor.ino || stat.mode !== ancestor.mode) fail('mutable_ancestor_identity_drift'); } const held = fs.fstatSync(snapshot.fd); const post = fs.lstatSync(snapshot.target); const bytes = Buffer.alloc(snapshot.identity.size); let offset = 0; while (offset < bytes.length) { const count = fs.readSync(snapshot.fd, bytes, offset, bytes.length - offset, offset); if (!count) fail('mutable_short_read'); offset += count; } if (held.dev !== snapshot.identity.dev || held.ino !== snapshot.identity.ino || held.mode !== snapshot.identity.mode || held.size !== snapshot.identity.size || held.nlink !== snapshot.identity.nlink || post.dev !== snapshot.identity.dev || post.ino !== snapshot.identity.ino || post.mode !== snapshot.identity.mode || post.size !== snapshot.identity.size || post.nlink !== snapshot.identity.nlink || sha256(bytes) !== snapshot.sha256 || !bytes.equals(snapshot.bytes)) fail('mutable_identity_drift'); }
async function replaceMutable(logicalPath, value, expectedSnapshot, checkpoint = () => {}) { const target = resolveAllowed(logicalPath, 'write'); if (target !== expectedSnapshot.target) fail('mutable_identity_drift'); checkpoint(); revalidateMutable(expectedSnapshot); const nextBytes = processBytes(value); const tempLogical = `mutable/.${path.basename(logicalPath)}.next-${process.pid}-${crypto.randomBytes(12).toString('hex')}`; const temp = resolveAllowed(tempLogical, 'write'); let handle; let final; try { handle = await fsp.open(temp, fs.constants.O_CREAT | fs.constants.O_EXCL | fs.constants.O_WRONLY | (fs.constants.O_NOFOLLOW ?? 0), 0o600); checkpoint(); record(tempLogical, 'write', 'allowed'); await handle.writeFile(nextBytes); checkpoint(); await handle.sync(); checkpoint(); const tempHeld = await handle.stat(); const tempPath = await fsp.lstat(temp); if (!tempHeld.isFile() || tempHeld.dev !== tempPath.dev || tempHeld.ino !== tempPath.ino || tempHeld.nlink !== 1 || tempHeld.mode !== tempPath.mode || (tempHeld.mode & 0o7777) !== 0o600 || tempHeld.size !== nextBytes.length) fail('mutable_temp_identity_drift'); revalidateMutable(expectedSnapshot); checkpoint(); fs.renameSync(temp, target); record(logicalPath, 'write', 'allowed'); const targetPost = fs.lstatSync(target); const heldPost = await handle.stat(); if (targetPost.dev !== tempHeld.dev || targetPost.ino !== tempHeld.ino || heldPost.dev !== tempHeld.dev || heldPost.ino !== tempHeld.ino || targetPost.mode !== tempHeld.mode || targetPost.nlink !== 1 || targetPost.size !== nextBytes.length) fail('mutable_replace_drift'); await handle.close(); handle = undefined; const parent = await fsp.open(path.dirname(target), fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0)); try { await parent.sync(); } finally { await parent.close(); } final = readMutableSnapshot(logicalPath); if (!final.bytes.equals(nextBytes)) fail('mutable_replace_drift'); return final; } catch (error) { closeMutable(final); throw error; } finally { await handle?.close().catch(() => {}); await fsp.unlink(temp).catch((error) => { if (error.code !== 'ENOENT') throw error; }); } }

const rowTypeByPath = new Map([['scenarios','scenario-array'],['presence','presence'],['personState','person-state'],['occlusion/body','occlusion-state'],['occlusion/leftFoot','occlusion-state'],['occlusion/rightFoot','occlusion-state'],['occlusion/leftHand','occlusion-state'],['occlusion/rightHand','occlusion-state'],['contact/left','contact-state'],['contact/right','contact-state'],['handObservability/left','hand-observability-state'],['handObservability/right','hand-observability-state'],['endpointObservability/leftWrist','endpoint-observability-state'],['endpointObservability/rightWrist','endpoint-observability-state'],['endpointObservability/leftAnkle','endpoint-observability-state'],['endpointObservability/rightAnkle','endpoint-observability-state'],['endpointObservability/head','endpoint-observability-state'],['subjectSelection/state','subject-state'],['subjectSelection/manualTargetId','manual-target-id'],['subjectSelection/anchor','anchor']]);
const valueEnums = new Map([['presence',['present','absent','unknown']],['person-state',['single_target','multiple_people','absent','unknown']],['occlusion-state',['observable','partial','occluded','out_of_frame','unknown']],['contact-state',['planted','moving','unknown']],['hand-observability-state',['observable','not_observable']],['endpoint-observability-state',['observable','not_observable']],['subject-state',['selected','absent','ambiguous','unknown']]]);
const SCENARIOS = new Set(['neutral','entry_exit','reacquire','arms_crossed','self_occlusion','side_view','back_view','fast_motion','jump','footwork','turn','leg_extension','distance_change','partial_body_crop','multi_person_background','duplicate_detection_challenge','hand_closeup','full_body_dance','upper_body_only']);
const PURPOSES = new Set(['full_clip_denominator','absence_reacquire','self_occlusion','fast_motion','contact_transition','multi_person','crop_out_of_frame','duplicate_detection','turning','hand_observability']);
function closedSortedVocabulary(value, vocabulary) { return Array.isArray(value) && value.length > 0 && new Set(value).size === value.length && value.every((item) => vocabulary.has(item)) && equal(value, [...value].sort(rawCompare)); }
function validTypedValue(type, value) { if (valueEnums.has(type)) return valueEnums.get(type).includes(value); if (type === 'manual-target-id') return value === null || typeof value === 'string' && value.length > 0; if (type === 'anchor') return value === null || value && typeof value === 'object' && !Array.isArray(value) && equal(Object.keys(value).sort(rawCompare), ['x','y']) && Number.isFinite(value.x) && Number.isFinite(value.y) && value.x >= 0 && value.x <= 1 && value.y >= 0 && value.y <= 1; if (type === 'scenario-array') return closedSortedVocabulary(value, SCENARIOS); if (type === 'purpose-array') return closedSortedVocabulary(value, PURPOSES); return false; }
function applyAction(worksheet, action) { if (['navigate','playback'].includes(action.action)) return; if (action.action === 'create-overlay') { if (action.windowId === `base-${action.clipId}` || worksheet.windows.some((window) => window.clipId === action.clipId && window.windowId === action.windowId)) fail('overlay_identity_invalid'); worksheet.windows.push({ windowId: action.windowId, clipId: action.clipId, startFrameIndex: action.startFrameIndex, endFrameIndexExclusive: action.endFrameIndexExclusive, origin: 'actor_overlay', purposeTags: { status: 'UNSET' }, scenarioTags: { status: 'UNSET' } }); return; } if (!['set','undo'].includes(action.action) || !validTypedValue(action.valueType, action.value)) fail('edit_action_invalid'); if (action.fieldPath.startsWith('/windowsById/')) { const match = /^\/windowsById\/([A-Za-z0-9][A-Za-z0-9._-]{0,63})\/(purposeTags|scenarioTags)$/u.exec(action.fieldPath); if (!match) fail('window_mutation_forbidden'); const [, id, child] = match; const window = worksheet.windows.find((item) => item.clipId === action.clipId && item.windowId === id); if (!window || action.startFrameIndex !== window.startFrameIndex || action.endFrameIndexExclusive !== window.endFrameIndexExclusive || window.origin === 'structural_base' && child !== 'scenarioTags' || window.origin === 'actor_overlay' && child === 'purposeTags' && action.value.includes('full_clip_denominator')) fail('window_target_mismatch'); const expected = child === 'purposeTags' ? 'purpose-array' : 'scenario-array'; if (action.valueType !== expected) fail('edit_value_type_mismatch'); window[child] = structuredClone(action.value); return; } const expectedType = rowTypeByPath.get(action.fieldPath); if (!expectedType || expectedType !== action.valueType) fail('edit_value_type_mismatch'); let changed = 0; for (const row of worksheet.rows) if (row.clipId === action.clipId && row.sourceFrameIndex >= action.startFrameIndex && row.sourceFrameIndex < action.endFrameIndexExclusive) { if (action.fieldPath === 'scenarios') row.scenarios = structuredClone(action.value); else { const parts = action.fieldPath.split('/'); let target = row.manualState; for (let index = 0; index < parts.length - 1; index += 1) target = target[parts[index]]; target[parts.at(-1)] = structuredClone(action.value); } changed += 1; } if (!changed) fail('edit_range_empty'); }
let trustedSeedSnapshot; let trustedJournalSnapshot; let trustedAttestationSnapshot = null; let mutableIntegrityLatched = false;
const unset = () => ({ status: 'UNSET' });
const initialManualState = () => ({ presence: unset(), personState: unset(), occlusion: { body: unset(), leftFoot: unset(), rightFoot: unset(), leftHand: unset(), rightHand: unset() }, contact: { left: unset(), right: unset() }, handObservability: { left: unset(), right: unset() }, endpointObservability: { leftWrist: unset(), rightWrist: unset(), leftAnkle: unset(), rightAnkle: unset(), head: unset() }, subjectSelection: { state: unset(), manualTargetId: unset(), anchor: unset() } });
function assertMutableHeader(document, artifactType) { const keys = artifactType === 'sam-goal-review-worksheet-v1' ? ['artifactType','schemaVersion','authorityClass','compilerInput','p0Authority','cycleId','mode','actorPseudonymSha256','bundleManifestByteSha256','sourceBinding','rulebookByteSha256','windows','rows'] : manifest.mode === 'adjudication-reveal' ? ['artifactType','schemaVersion','authorityClass','compilerInput','p0Authority','cycleId','mode','actorPseudonymSha256','bundleManifestByteSha256','revealReceiptByteSha256','events'] : ['artifactType','schemaVersion','authorityClass','compilerInput','p0Authority','cycleId','mode','actorPseudonymSha256','bundleManifestByteSha256','events']; exactKeys(document, keys, 'mutable_document_not_closed'); if (document.artifactType !== artifactType || document.schemaVersion !== 1 || document.authorityClass !== 'process-evidence-only' || document.compilerInput !== false || document.p0Authority !== false || document.cycleId !== manifest.cycleId || document.mode !== manifest.mode || document.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || document.bundleManifestByteSha256 !== sha256(manifestBytes) || manifest.mode === 'adjudication-reveal' && document.revealReceiptByteSha256 !== revealReceiptByteSha256) fail('mutable_document_binding_invalid'); }
function assertJournalEvent(event, index, worksheet) { if (event.sequence !== index + 1) fail('journal_sequence_invalid'); if (['navigate','playback'].includes(event.action)) { exactKeys(event, ['sequence','action','clipId','sourceFrameIndex'], 'journal_event_not_closed'); if (!worksheet.rows.some((row) => row.clipId === event.clipId && row.sourceFrameIndex === event.sourceFrameIndex)) fail('journal_navigation_identity_invalid'); return; } const keys = event.action === 'create-overlay' ? ['sequence','action','actorPseudonymSha256','clipId','startFrameIndex','endFrameIndexExclusive','windowId','lockedIdentity'] : ['sequence','action','actorPseudonymSha256','clipId','startFrameIndex','endFrameIndexExclusive','fieldPath','valueType','value','lockedIdentity']; exactKeys(event, keys, 'journal_event_not_closed'); if (event.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || !Number.isSafeInteger(event.startFrameIndex) || !Number.isSafeInteger(event.endFrameIndexExclusive) || event.startFrameIndex < 0 || event.startFrameIndex >= event.endFrameIndexExclusive) fail('journal_event_binding_invalid'); assertIdentity(event.lockedIdentity); const clipRows = worksheet.rows.filter((row) => row.clipId === event.clipId); const locked = clipRows.find((row) => row.sourceFrameIndex === event.lockedIdentity.sourceFrameIndex); if (!locked || event.endFrameIndexExclusive > clipRows.length || !equal(exactIdentity(locked), event.lockedIdentity) || locked.sourceFrameIndex < event.startFrameIndex || locked.sourceFrameIndex >= event.endFrameIndexExclusive) fail('journal_locked_identity_invalid'); }
function latchMutableIntegrity(error) { mutableIntegrityLatched = true; throw error; }
function currentWorksheet() { if (mutableIntegrityLatched) fail('mutable_integrity_latched'); try { revalidateMutable(trustedSeedSnapshot); revalidateMutable(trustedJournalSnapshot); const seed = parseJson(trustedSeedSnapshot.bytes, { canonicalProcess: true }); const journal = parseJson(trustedJournalSnapshot.bytes, { canonicalProcess: true }); assertMutableHeader(journal, 'sam-goal-review-edit-journal-v1');
  if (manifest.mode === 'adjudication-reveal') { const publicState = { evaluationContract: parseJson(readImmutable('immutable/authority/evaluation-contract.json')), labelSchema: parseJson(readImmutable('immutable/authority/label-schema.json')), authoringSchema: parseJson(readImmutable('immutable/authority/authoring-schema.json')), sourceInventory, decoderRows, publicPins: manifest.publicPins }; const replay = revealCore.replayAdjudicationJournal({ journal, skeleton: seed, reviewA: revealReviewA, reviewB: revealReviewB, c0Rows: revealC0.rows, c0Windows: revealC0.windows, publicState, expectedActorPseudonym: manifest.actorPseudonymSha256, expectedRevealReceiptByteSha256: revealReceiptByteSha256 }); revalidateMutable(trustedSeedSnapshot); revalidateMutable(trustedJournalSnapshot); return { worksheet: { artifactType: 'sam-goal-adjudication-session-view-v1', schemaVersion: 1, cycleId: manifest.cycleId, mode: manifest.mode, actorPseudonymSha256: manifest.actorPseudonymSha256, sourceBinding: manifest.sourceBinding, rows: revealC0.rows, windows: revealC0.windows, disagreements: revealSkeleton.disagreements, decisions: replay.finalState.decisions, dispositionRecords: replay.finalState.dispositionRecords }, sessionFinalState: replay.finalState, replay, journal, seedSnapshot: trustedSeedSnapshot, journalSnapshot: trustedJournalSnapshot }; }
  assertMutableHeader(seed, 'sam-goal-review-worksheet-v1'); if (!Array.isArray(seed.rows) || !Array.isArray(seed.windows) || !Array.isArray(journal.events) || seed.rows.length !== 6711) fail('mutable_document_invalid'); for (const [index, event] of journal.events.entries()) { assertJournalEvent(event, index, seed); applyAction(seed, event); } revalidateMutable(trustedSeedSnapshot); revalidateMutable(trustedJournalSnapshot); return { worksheet: seed, sessionFinalState: seed, journal, seedSnapshot: trustedSeedSnapshot, journalSnapshot: trustedJournalSnapshot }; } catch (error) { latchMutableIntegrity(error); } }
function closeWorksheet(_value) {}

function responseHeaders(type) { return { 'content-type': type, 'content-security-policy': CSP, 'x-content-type-options': 'nosniff', 'cache-control': 'no-store' }; }
function send(res, status, bytes, type = 'application/json; charset=utf-8') { if (res.headersSent || res.destroyed) return; res.writeHead(status, responseHeaders(type)); res.end(bytes); }
async function requestBody(req) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > 1024 * 1024) fail('request_too_large'); chunks.push(Buffer.from(chunk)); } return Buffer.concat(chunks); }
function logicalFromUrl(url) { if (url === '/') return 'immutable/viewer/index.html'; if (url === '/app.js') return 'immutable/viewer/app.js'; if (url === '/exact-still-decoder.js') return 'immutable/viewer/exact-still-decoder.js'; if (url === '/style.css') return 'immutable/viewer/style.css'; if (url === '/rulebook.md') return 'immutable/rulebook.md'; if (url.startsWith('/sources/') && !url.includes('?') && !url.includes('#')) { let name; try { name = decodeURIComponent(url.slice('/sources/'.length)); } catch { return null; } if (!/^[A-Za-z0-9][A-Za-z0-9._-]*\.mp4$/u.test(name)) return null; return `immutable/sources/${name}`; } return null; }
const exactIdentity = (row) => ({ clipId: row.clipId, sourceFrameIndex: row.sourceFrameIndex, ptsTicks: row.ptsTicks, timeBase: row.timeBase, loopEpoch: row.loopEpoch });
function assertIdentity(identity) { exactKeys(identity, ['clipId','sourceFrameIndex','ptsTicks','timeBase','loopEpoch'], 'frame_identity_invalid'); exactKeys(identity.timeBase, ['numerator','denominator'], 'frame_identity_invalid'); }

function initializeTrustedMutableState() {
  trustedSeedSnapshot = manifest.mode === 'adjudication-reveal' ? readMutableSnapshot('fixed/disagreement-skeleton.json', { expectedMode: 0o400 }) : readMutableSnapshot('mutable/worksheet-seed.json'); trustedJournalSnapshot = readMutableSnapshot(manifest.mode === 'adjudication-reveal' ? 'mutable/adjudication-journal.json' : 'mutable/edit-journal.json');
  try {
    for (const logical of ['mutable/actor-attestation.json','mutable/access-evidence.json']) { try { fs.lstatSync(resolveAllowed(logical, 'read')); fail('bundle_session_already_started'); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
    const seed = parseJson(trustedSeedSnapshot.bytes, { canonicalProcess: true }); const journal = parseJson(trustedJournalSnapshot.bytes, { canonicalProcess: true }); assertMutableHeader(journal, 'sam-goal-review-edit-journal-v1');
    if (manifest.mode === 'adjudication-reveal') { const expectedJournal = { artifactType: 'sam-goal-review-edit-journal-v1', schemaVersion: 1, authorityClass: 'process-evidence-only', compilerInput: false, p0Authority: false, cycleId: manifest.cycleId, mode: manifest.mode, actorPseudonymSha256: manifest.actorPseudonymSha256, bundleManifestByteSha256: sha256(manifestBytes), revealReceiptByteSha256, events: [] }; if (!equal(seed, revealSkeleton) || !equal(journal, expectedJournal)) fail('bundle_initial_mutable_state_invalid'); currentWorksheet(); return; }
    assertMutableHeader(seed, 'sam-goal-review-worksheet-v1');
    const expectedSourceOrder = [...new Set(decoderRows.map((row) => row.clipId))]; if (!equal(manifest.sourceBinding.sources.map((source) => source.clipId), expectedSourceOrder)) fail('source_binding_order_invalid'); const expectedRows = decoderRows.map((identity) => ({ ...exactIdentity(identity), scenarios: unset(), manualState: initialManualState() })); const expectedWindows = manifest.sourceBinding.sources.map((source) => ({ windowId: `base-${source.clipId}`, clipId: source.clipId, startFrameIndex: 0, endFrameIndexExclusive: sourceMetadata.get(source.clipId).rowCount, origin: 'structural_base', purposeTags: ['full_clip_denominator'], scenarioTags: unset() }));
    const expectedSeed = { artifactType: 'sam-goal-review-worksheet-v1', schemaVersion: 1, authorityClass: 'process-evidence-only', compilerInput: false, p0Authority: false, cycleId: manifest.cycleId, mode: manifest.mode, actorPseudonymSha256: manifest.actorPseudonymSha256, bundleManifestByteSha256: sha256(manifestBytes), sourceBinding: manifest.sourceBinding, rulebookByteSha256: manifest.rulebookByteSha256, windows: expectedWindows, rows: expectedRows };
    const expectedJournal = { artifactType: 'sam-goal-review-edit-journal-v1', schemaVersion: 1, authorityClass: 'process-evidence-only', compilerInput: false, p0Authority: false, cycleId: manifest.cycleId, mode: manifest.mode, actorPseudonymSha256: manifest.actorPseudonymSha256, bundleManifestByteSha256: sha256(manifestBytes), events: [] };
    if (!equal(seed, expectedSeed) || !equal(journal, expectedJournal)) fail('bundle_initial_mutable_state_invalid'); revalidateMutable(trustedSeedSnapshot); revalidateMutable(trustedJournalSnapshot);
  } catch (error) { closeMutable(trustedSeedSnapshot); closeMutable(trustedJournalSnapshot); throw error; }
}
initializeTrustedMutableState();

let phase = 'open'; let closeVersion = 0; let activeSession = null; let sessionEpoch = 0; let activeLock = null; let lastClientGeneration = 0; let issuedGenerationFloor = 0; let lockSequence = 0; let evidenceFinalized = false; let serialTail = Promise.resolve(); let signalExitCode = null; let allowedOrigin = null; let allowedHost = null;
function enqueue(task) { const current = serialTail.then(task, task); serialTail = current.catch(() => {}); return current; }
function openMutation(task, requestSession) { if (phase !== 'open') fail('session_closed'); const version = closeVersion; const checkpoint = () => { if (phase !== 'open' || closeVersion !== version || !activeSession || activeSession.sessionId !== requestSession.sessionId) fail('session_closed'); }; return enqueue(async () => { checkpoint(); return task(checkpoint); }); }
function assertMutationRequest(req) { if (!allowedOrigin || !activeSession || req.headers.origin !== allowedOrigin || req.headers.host !== allowedHost || req.headers['content-type'] !== 'application/json' || req.headers['x-sam-goal-csrf'] !== activeSession.csrfToken || req.headers['x-sam-goal-session'] !== activeSession.sessionId) fail('same_origin_request_required'); return activeSession; }
function requestClose() { if (phase !== 'open') fail('session_closed'); closeVersion += 1; phase = 'closing'; }
function assertSealAttestation() { if (!trustedAttestationSnapshot || mutableIntegrityLatched) fail('actor_attestation_missing'); try { revalidateMutable(trustedAttestationSnapshot); const value = parseJson(trustedAttestationSnapshot.bytes, { canonicalProcess: true }); exactKeys(value, ['actorPseudonymSha256','actorDeclaredNoOutsideInput','cycleId'], 'actor_attestation_invalid'); if (value.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || value.cycleId !== manifest.cycleId || value.actorDeclaredNoOutsideInput !== true) fail('actor_attestation_invalid'); revalidateMutable(trustedAttestationSnapshot); } catch (error) { mutableIntegrityLatched = true; throw error; } }

async function sealEvidence() {
  if (evidenceFinalized) return; verifyImmutableSet(); const state = currentWorksheet(); let attestationSnapshot;
  try {
    assertSealAttestation(); attestationSnapshot = trustedAttestationSnapshot; const attestation = parseJson(attestationSnapshot.bytes, { canonicalProcess: true }); exactKeys(attestation, ['actorPseudonymSha256','actorDeclaredNoOutsideInput','cycleId'], 'actor_attestation_invalid');
    if (attestation.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || attestation.cycleId !== manifest.cycleId || attestation.actorDeclaredNoOutsideInput !== true) fail('actor_attestation_invalid');
    revalidateMutable(attestationSnapshot); revalidateMutable(state.seedSnapshot); revalidateMutable(state.journalSnapshot);
    const evidencePath = resolveAllowed('mutable/access-evidence.json', 'write'); try { fs.lstatSync(evidencePath); fail('access_evidence_exists'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    const tempLogical = `mutable/.access-evidence.seal-${process.pid}-${crypto.randomBytes(12).toString('hex')}`; const temp = resolveAllowed(tempLogical, 'write'); let handle;
    try {
      handle = await fsp.open(temp, fs.constants.O_CREAT | fs.constants.O_EXCL | fs.constants.O_WRONLY | (fs.constants.O_NOFOLLOW ?? 0), 0o600); record(tempLogical, 'write', 'allowed');
      revalidateMutable(attestationSnapshot); revalidateMutable(state.seedSnapshot); revalidateMutable(state.journalSnapshot); verifyImmutableSet();
      // The evidence cut includes the complete commit and post-link verification operations before
      // bytes are materialized. If either operation fails, no evidence file is committed.
      record('mutable/access-evidence.json', 'write', 'allowed'); record('mutable/access-evidence.json', 'read', 'allowed');
      const evidence = { artifactType: 'sam-goal-review-access-evidence-v1', schemaVersion: 1, authorityClass: 'process-evidence-only', compilerInput: false, p0Authority: false, cycleId: manifest.cycleId, mode: manifest.mode, actorPseudonymSha256: manifest.actorPseudonymSha256, presentationContractSha256: currentPresentationContractSha256, bundleManifestByteSha256: sha256(manifestBytes), immutableAssetSetSha256: manifest.immutableAssetSetSha256, fixedInputSetSha256: manifest.mode === 'adjudication-reveal' ? revealFixedInputSetSha256 : sha256(processBytes([])), sessionSeedByteSha256: state.seedSnapshot.sha256, sessionFinalStateByteSha256: sha256(processBytes(state.sessionFinalState)), editJournalByteSha256: state.journalSnapshot.sha256, actorAttestationByteSha256: attestationSnapshot.sha256, filesystemAllowlist: [...new Set([manifestLogical, ...immutable.keys(), ...fixed.keys(), ...manifest.mutableLogicalRoots])].sort(rawCompare), networkAllowlist: ['127.0.0.1','::1','localhost'], actualOpenEvents: structuredClone(events), cspHeaders: { 'content-security-policy': CSP }, negativeProbeResults, outsideInputAttestation: { coordinatorProvidedRuntimeDataAfterSpawn: false, actorDeclaredNoOutsideInput: true } };
      const bytes = processBytes(evidence); await handle.writeFile(bytes); await handle.sync(); await handle.close(); handle = undefined; await fsp.link(temp, evidencePath); await fsp.unlink(temp);
      const parent = await fsp.open(path.dirname(evidencePath), fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0)); try { await parent.sync(); } finally { await parent.close(); }
      const final = readMutableSnapshot('mutable/access-evidence.json', { recordEvent: false }); try { if (!final.bytes.equals(bytes) || final.sha256 !== sha256(bytes)) fail('access_evidence_commit_drift'); } finally { closeMutable(final); }
      evidenceFinalized = true;
    } finally { await handle?.close().catch(() => {}); await fsp.unlink(temp).catch((error) => { if (error.code !== 'ENOENT') throw error; }); }
  } finally { closeWorksheet(state); }
}

const server = http.createServer(async (req, res) => {
  try {
    if (!allowedHost || req.headers.host !== allowedHost || req.headers.origin !== undefined && req.headers.origin !== allowedOrigin) fail('same_origin_request_required');
    const requestSession = req.method === 'POST' ? assertMutationRequest(req) : null;
    if (req.method === 'GET' && req.url === '/api/session') {
      if (req.headers['sec-fetch-site'] !== 'same-origin' || typeof req.headers.referer !== 'string' || !req.headers.referer.startsWith(`${allowedOrigin}/`) || phase !== 'open') fail('same_origin_request_required');
      const bootstrap = await enqueue(async () => { if (phase !== 'open') fail('session_closed'); const start = Math.max(issuedGenerationFloor, lastClientGeneration) + 1; issuedGenerationFloor = start + 999_999; if (!Number.isSafeInteger(issuedGenerationFloor)) fail('client_generation_exhausted'); if (activeLock) { record(`session/frame-lock/${activeLock.lockSequence}`, 'unlock', 'allowed'); activeLock = null; } activeSession = { sessionId: crypto.randomBytes(32).toString('hex'), csrfToken: crypto.randomBytes(32).toString('hex'), epoch: ++sessionEpoch }; return { status: 'session_bootstrap', sessionId: activeSession.sessionId, csrfToken: activeSession.csrfToken, sessionEpoch: activeSession.epoch, generationBase: start - 1 }; });
      return send(res, 200, processBytes(bootstrap));
    }
    if (req.method === 'GET' && req.url === '/api/worksheet') { const state = await enqueue(async () => currentWorksheet()); try { return send(res, 200, processBytes(state.worksheet)); } finally { closeWorksheet(state); } }
    if (req.method === 'GET' && req.url === '/api/manifest') return send(res, 200, manifestBytes);
    if (req.method === 'POST' && req.url === '/api/lock') return await openMutation(async (checkpoint) => { const claim = parseJson(await requestBody(req)); checkpoint(); exactKeys(claim, ['canvasHeight','canvasWidth','clientGeneration','codedHeight','codedWidth','displayHeight','displayWidth','identity','sampleToken','sourceByteSha256'], 'frame_lock_claim_invalid'); assertIdentity(claim.identity); if (!Number.isSafeInteger(claim.clientGeneration) || claim.clientGeneration <= lastClientGeneration || claim.clientGeneration > issuedGenerationFloor || !Number.isSafeInteger(claim.sampleToken) || !['canvasWidth','canvasHeight','codedWidth','codedHeight','displayWidth','displayHeight'].every((key) => Number.isSafeInteger(claim[key]) && claim[key] > 0)) fail('frame_lock_claim_invalid'); const state = currentWorksheet(); try { const row = state.worksheet.rows.find((item) => item.clipId === claim.identity.clipId && item.sourceFrameIndex === claim.identity.sourceFrameIndex); const metadata = row && sourceMetadata.get(row.clipId); if (!row || !metadata || !equal(exactIdentity(row), claim.identity) || claim.sampleToken !== row.sourceFrameIndex || claim.sourceByteSha256 !== metadata.sourceByteSha256 || claim.codedWidth !== metadata.codedWidth || claim.codedHeight !== metadata.codedHeight || claim.displayWidth !== metadata.displayWidth || claim.displayHeight !== metadata.displayHeight || claim.canvasWidth !== metadata.displayWidth || claim.canvasHeight !== metadata.displayHeight) fail('frame_lock_identity_invalid'); checkpoint(); if (activeLock) record(`session/frame-lock/${activeLock.lockSequence}`, 'unlock', 'allowed'); const nonce = crypto.randomBytes(32).toString('hex'); lastClientGeneration = claim.clientGeneration; activeLock = { nonce, identity: exactIdentity(row), clientGeneration: claim.clientGeneration, lockSequence: ++lockSequence }; record(`session/frame-lock/${lockSequence}`, 'lock', 'allowed'); return send(res, 200, processBytes({ status: 'exact_frame_lock_issued', lockNonce: nonce, lockSequence, clientGeneration: claim.clientGeneration })); } finally { closeWorksheet(state); } }, requestSession);
    if (req.method === 'POST' && req.url === '/api/unlock') return await openMutation(async (checkpoint) => { const request = parseJson(await requestBody(req)); checkpoint(); exactKeys(request, ['clientGeneration','lockNonce'], 'unlock_request_invalid'); if (activeLock && request.clientGeneration === activeLock.clientGeneration && request.lockNonce === activeLock.nonce) { record(`session/frame-lock/${activeLock.lockSequence}`, 'unlock', 'allowed'); activeLock = null; return send(res, 200, processBytes({ status: 'frame_lock_invalidated', clientGeneration: request.clientGeneration })); } return send(res, 200, processBytes({ status: 'stale_frame_lock_ignored', clientGeneration: request.clientGeneration })); }, requestSession);
    if (req.method === 'POST' && req.url === '/api/attest') return await openMutation(async (checkpoint) => { if (trustedAttestationSnapshot) fail('actor_attestation_already_recorded'); const attestation = parseJson(await requestBody(req)); checkpoint(); exactKeys(attestation, ['actorPseudonymSha256','actorDeclaredNoOutsideInput','cycleId'], 'actor_attestation_invalid'); if (attestation.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || attestation.cycleId !== manifest.cycleId || attestation.actorDeclaredNoOutsideInput !== true) fail('actor_attestation_invalid'); const bytes = processBytes(attestation); const target = resolveAllowed('mutable/actor-attestation.json', 'write'); const tempLogical = `mutable/.actor-attestation.next-${process.pid}-${crypto.randomBytes(12).toString('hex')}`; const temp = resolveAllowed(tempLogical, 'write'); let handle; let snapshot; try { handle = await fsp.open(temp, fs.constants.O_CREAT | fs.constants.O_EXCL | fs.constants.O_WRONLY | (fs.constants.O_NOFOLLOW ?? 0), 0o600); checkpoint(); record(tempLogical, 'write', 'allowed'); await handle.writeFile(bytes); checkpoint(); await handle.sync(); checkpoint(); const held = await handle.stat(); const atPath = await fsp.lstat(temp); if (!held.isFile() || held.dev !== atPath.dev || held.ino !== atPath.ino || held.nlink !== 1 || held.mode !== atPath.mode || held.size !== bytes.length) fail('mutable_temp_identity_drift'); checkpoint(); fs.linkSync(temp, target); fs.unlinkSync(temp); record('mutable/actor-attestation.json', 'write', 'allowed'); await handle.close(); handle = undefined; const parent = await fsp.open(path.dirname(target), fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW ?? 0)); try { await parent.sync(); } finally { await parent.close(); } snapshot = readMutableSnapshot('mutable/actor-attestation.json'); if (!snapshot.bytes.equals(bytes)) fail('actor_attestation_commit_drift'); trustedAttestationSnapshot = snapshot; snapshot = undefined; return send(res, 200, processBytes({ status: 'actor_attestation_recorded' })); } catch (error) { closeMutable(snapshot); if (fs.existsSync(target)) mutableIntegrityLatched = true; throw error; } finally { await handle?.close().catch(() => {}); await fsp.unlink(temp).catch((error) => { if (error.code !== 'ENOENT') throw error; }); } }, requestSession);
    if (req.method === 'POST' && req.url === '/api/edit' && manifest.mode === 'adjudication-reveal') return await openMutation(async (checkpoint) => { const action = parseJson(await requestBody(req)); checkpoint(); const exact = action.action === 'set-decision' ? ['action','actorPseudonymSha256','clientGeneration','path','valueType','decision'] : ['action','actorPseudonymSha256','clientGeneration','coordinateKind','path','deviationClass','disposition','rationale']; exactKeys(action, exact, 'adjudication_action_invalid'); if (!['set-decision','set-disposition'].includes(action.action) || action.actorPseudonymSha256 !== manifest.actorPseudonymSha256 || !Number.isSafeInteger(action.clientGeneration) || action.clientGeneration <= lastClientGeneration || action.clientGeneration > issuedGenerationFloor) fail('adjudication_action_invalid'); const state = currentWorksheet(); try { const { clientGeneration, ...journalAction } = action; const nextJournalValue = structuredClone(state.journal); nextJournalValue.events.push({ sequence: nextJournalValue.events.length + 1, ...journalAction }); const publicState = { evaluationContract: parseJson(readImmutable('immutable/authority/evaluation-contract.json')), labelSchema: parseJson(readImmutable('immutable/authority/label-schema.json')), authoringSchema: parseJson(readImmutable('immutable/authority/authoring-schema.json')), sourceInventory, decoderRows, publicPins: manifest.publicPins }; const currentDispositionState = revealCore.replayAdjudicationJournal({ journal: nextJournalValue, skeleton: revealSkeleton, reviewA: revealReviewA, reviewB: revealReviewB, c0Rows: revealC0.rows, c0Windows: revealC0.windows, publicState, expectedActorPseudonym: manifest.actorPseudonymSha256, expectedRevealReceiptByteSha256: revealReceiptByteSha256 }); revalidateMutable(state.seedSnapshot); checkpoint(); let nextJournal; try { nextJournal = await replaceMutable('mutable/adjudication-journal.json', nextJournalValue, state.journalSnapshot, checkpoint); } catch (error) { mutableIntegrityLatched = true; throw error; } const previousJournal = trustedJournalSnapshot; trustedJournalSnapshot = nextJournal; closeMutable(previousJournal); lastClientGeneration = clientGeneration; return send(res, 200, processBytes({ status: 'explicit_adjudication_recorded', sequence: nextJournalValue.events.length, clientGeneration, decisionsComplete: currentDispositionState.decisionsComplete, dispositionsComplete: currentDispositionState.dispositionsComplete })); } finally { closeWorksheet(state); } }, requestSession);
    if (req.method === 'POST' && req.url === '/api/edit') return await openMutation(async (checkpoint) => { const action = parseJson(await requestBody(req)); checkpoint(); const exact = action.action === 'create-overlay' ? ['action','actorPseudonymSha256','clientGeneration','clipId','startFrameIndex','endFrameIndexExclusive','windowId','lockedIdentity','lockNonce'] : ['action','actorPseudonymSha256','clientGeneration','clipId','startFrameIndex','endFrameIndexExclusive','fieldPath','valueType','value','lockedIdentity','lockNonce']; exactKeys(action, exact, 'edit_action_invalid'); if (!['set','undo','create-overlay'].includes(action.action) || !Number.isSafeInteger(action.clientGeneration) || !Number.isSafeInteger(action.startFrameIndex) || !Number.isSafeInteger(action.endFrameIndexExclusive) || action.startFrameIndex < 0 || action.startFrameIndex >= action.endFrameIndexExclusive || action.action === 'create-overlay' && !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u.test(action.windowId) || action.actorPseudonymSha256 !== manifest.actorPseudonymSha256) fail('edit_action_invalid'); assertIdentity(action.lockedIdentity); if (!activeLock || action.clientGeneration !== activeLock.clientGeneration || action.lockNonce !== activeLock.nonce || !equal(action.lockedIdentity, activeLock.identity)) fail('locked_identity_invalid'); const state = currentWorksheet(); try { const clipRows = state.worksheet.rows.filter((row) => row.clipId === action.clipId); const lockedRow = clipRows.find((row) => row.sourceFrameIndex === action.lockedIdentity.sourceFrameIndex); if (!lockedRow || action.endFrameIndexExclusive > clipRows.length || !equal(exactIdentity(lockedRow), action.lockedIdentity) || lockedRow.sourceFrameIndex < action.startFrameIndex || lockedRow.sourceFrameIndex >= action.endFrameIndexExclusive) fail('locked_identity_invalid'); applyAction(state.worksheet, action); const { lockNonce: _nonce, clientGeneration: _generation, ...journalAction } = action; state.journal.events.push({ sequence: state.journal.events.length + 1, ...journalAction }); revalidateMutable(state.seedSnapshot); checkpoint(); let nextJournal; try { nextJournal = await replaceMutable('mutable/edit-journal.json', state.journal, state.journalSnapshot, checkpoint); } catch (error) { mutableIntegrityLatched = true; throw error; } const previousJournal = trustedJournalSnapshot; trustedJournalSnapshot = nextJournal; closeMutable(previousJournal); record(`session/frame-lock/${activeLock.lockSequence}`, 'unlock', 'allowed'); activeLock = null; return send(res, 200, processBytes({ status: 'explicit_edit_recorded', sequence: state.journal.events.length, clientGeneration: action.clientGeneration })); } finally { closeWorksheet(state); } }, requestSession);
    if (req.method === 'POST' && req.url === '/api/end-session') { assertSealAttestation(); requestClose(); return await enqueue(async () => {
      activeLock = null; await sealEvidence(); phase = 'closed';
      const listenerClosed = new Promise((resolve, reject) => {
        res.once('finish', () => server.close((error) => error ? reject(error) : resolve()));
        res.setHeader('connection', 'close'); send(res, 200, processBytes({ status: 'access_evidence_sealed' }));
      });
      await listenerClosed; verifyImmutableSet(); revalidateMutable(trustedSeedSnapshot); revalidateMutable(trustedJournalSnapshot); revalidateMutable(trustedAttestationSnapshot);
      process.stdout.write(processBytes({ status: 'review_session_final' }));
      const acknowledgement = await new Promise((resolve, reject) => {
        const timer = setTimeout(() => reject(Object.assign(new Error('coordinator_ack_timeout'), { code: 'coordinator_ack_timeout' })), PRIVATE_PROTOCOL_TIMEOUT_MS);
        const chunks = []; let bytes = 0;
        const onData = (chunk) => { chunks.push(Buffer.from(chunk)); bytes += chunk.length; if (bytes > 4 || Buffer.concat(chunks).includes(0x0a)) { cleanup(); resolve(Buffer.concat(chunks)); } };
        const onEnd = () => { cleanup(); reject(Object.assign(new Error('coordinator_ack_missing'), { code: 'coordinator_ack_missing' })); };
        const cleanup = () => { clearTimeout(timer); process.stdin.off('data', onData); process.stdin.off('end', onEnd); };
        process.stdin.on('data', onData); process.stdin.once('end', onEnd); process.stdin.resume();
      });
      if (!acknowledgement.equals(Buffer.from('ACK\n'))) fail('coordinator_ack_invalid');
      process.stdin.pause();
      closeMutable(trustedSeedSnapshot); closeMutable(trustedJournalSnapshot); closeMutable(trustedAttestationSnapshot);
    }); }
    if (req.method === 'GET') { const logical = logicalFromUrl(req.url); if (logical) { const extension = path.extname(logical); const type = extension === '.html' ? 'text/html; charset=utf-8' : extension === '.js' ? 'text/javascript; charset=utf-8' : extension === '.css' ? 'text/css; charset=utf-8' : extension === '.md' ? 'text/markdown; charset=utf-8' : 'video/mp4'; return send(res, 200, readImmutable(logical), type); } }
    return send(res, 404, processBytes({ status: 'not_found' }));
  } catch (error) {
    const failure = processBytes({ status: 'failed', code: error.code ?? 'request_failed' });
    if (req.method === 'POST' && req.url === '/api/end-session') {
      closeVersion += 1; phase = 'closed'; activeLock = null; res.setHeader('connection', 'close');
      const fallback = setTimeout(() => process.exit(1), 2_000); fallback.unref(); res.once('finish', () => server.close(() => { clearTimeout(fallback); process.exit(1); })); send(res, 409, failure); return;
    }
    return send(res, phase === 'open' ? 400 : 409, failure);
  }
});
server.on('connection', (socket) => { const host = socket.remoteAddress === '::ffff:127.0.0.1' ? '127.0.0.1' : socket.remoteAddress; record(`${host}:${socket.remotePort}`, 'connect', host === '127.0.0.1' || host === '::1' ? 'allowed' : 'denied'); if (!['127.0.0.1','::1'].includes(host)) socket.destroy(); });
server.listen(0, '127.0.0.1', () => {
  const address = server.address(); allowedHost = `127.0.0.1:${address.port}`; allowedOrigin = `http://${allowedHost}`; record(allowedHost, 'bind', 'allowed');
  if (testFault === 'oversize-ready') process.stdout.write('x'.repeat(16_384));
  else if (testFault === 'duplicate-key-ready') process.stdout.write(`{"status":"serving_source_only_bundle","status":"serving_source_only_bundle","host":"127.0.0.1","port":${address.port},"csp":${JSON.stringify(CSP)}}\n`);
  else if (testFault === 'malformed-ready') process.stdout.write('{malformed-ready\n');
  else {
    process.stdout.write(processBytes({ status: 'serving_source_only_bundle', host: '127.0.0.1', port: address.port, csp: CSP }));
    if (testFault === 'extra-ready-line') process.stdout.write(processBytes({ status: 'unexpected_extra_private_line' }));
    if (testFault === 'crash-after-ready') setTimeout(() => process.exit(7), 250);
  }
});

async function stopForSignal(signal) { if (signalExitCode !== null) return; signalExitCode = signal === 'SIGINT' ? 130 : 143; if (phase === 'open') { closeVersion += 1; phase = 'closing'; } const fallback = setTimeout(() => process.exit(signalExitCode), 2000); fallback.unref(); try { await enqueue(async () => { activeLock = null; phase = 'closed'; }); } catch {} finally { server.close(() => { clearTimeout(fallback); process.exit(signalExitCode); }); } }
process.once('SIGINT', () => { void stopForSignal('SIGINT'); });
process.once('SIGTERM', () => { void stopForSignal('SIGTERM'); });
